version: "3.7"
services:
  personalrecord-db:
    image: mysql
    restart: always
    networks:
      - personalrecord-network
    environment:
      - MYSQL_ROOT_PASSWORD=rootroot
      - MYSQL_DATABASE=mediscreen
    volumes:
      - ./microservice_PersonnalReccord/data:/docker-entrypoint-initdb.d

  personalrecord:
    build: ./microservice_PersonnalReccord
    restart: always
    ports:
      - 8081:8081
    networks:
      - personalrecord-network
    environment:
      - spring.datasource.url=jdbc:mysql://personalrecord-db:3306/mediscreen?serverTimezone=UTC
    depends_on:
      - personalrecord-db



  practitionernote-db:
    image: mongo
    networks:
      - personalrecord-network

  practitionernote:
    build: ./microservice_PractitionerNote
    ports:
      - 8082:8082
    networks:
      - personalrecord-network
    environment:
      - spring.data.mongodb.host=practitionernote-db
    depends_on:
      - practitionernote-db



  diabetesreport:
    build: ./microservice_DiabetesReport
    ports:
      - 8083:8083
    networks:
      - personalrecord-network
    depends_on:
      - personalrecord
      - practitionernote



  clientui:
    build: ./microservice_ClientUI
    ports:
      - 8080:8080
    networks:
      - personalrecord-network
    depends_on:
      - personalrecord
      - practitionernote
      - diabetesreport

networks:
  personalrecord-network: